leanbean-proxy:
  image: wisobi/leanbean-nginx
  ports:
    - "80:80"
  links:
    - leanbean-api
leanbean-api:
  image: wisobi/leanbean-tomcat
  links:
   - leanbean-db
leanbean-db:
  image: wisobi/leanbean-mysql