sudo: required

language: ruby

services:
- docker

before_install:
- cp -r leanbean-api leanbean-google leanbean-mobile leanbean-docker/build
- docker build -t wisobi/leanbean-build leanbean-docker/build
- docker pull wisobi/leanbean-nginx
- docker pull wisobi/leanbean-tomcat
- docker pull wisobi/leanbean-mysql

install:
- cd leanbean-docker
- docker-compose up -d
- cd ..

before_script:
 # Deploy LeanBean API to test container
- docker run --name leanbean-buid wisobi/leanbean-build /bin/sh -c "cd /opt/leanbean/leanbean-api/; bash deploy-tomcat.sh test"

script:
- bash test.sh leanbean-proxy

after_success:
# Deploy LeanBean API
#- docker run --name leanbean-buid wisobi/leanbean-build /bin/sh -c "cd /opt/leanbean/leanbean-api/; bash deploy-tomcat.sh prod"
# Deploy LeanBean Android to alpha track
- docker run wisobi/leanbean-build /bin/sh -c "cd /opt/leanbean/leanbean-google; bash deploy-android.sh"

after_failure: true

before_deploy:
- bash update-versions.sh

after_deploy: true

after_script:
- docker-compose stop
- docker-compose rm -f

env:
  global:
  # travis encrypt TOMCAT_USER=username
  - secure: iSFIP6uB11Ba9t3ld+UXgyFEsc0/gF0nGspkj2kvuX7Hk2bOybQ+L+atITFss9dFrYJXCzKQOu5S6G0OY2icKpT6l2JA/4YesZmTBJoBAr+4rwVngTy7r+EpGNSVgRA0gecAjGP/HQbD5Ae0LPXRGueeBv0Og1SzuMHpUzNN4g4=
  # travis encrypt TOMCAT_PASS=password
  - secure: S6xkNhNRvlt5UUFK416dCRIpv8eWijf6ecIWNdc8c4HpKoc7F9FknsGcyRwdBHH9BxXbXKxRrFIXRDtunRkuprmmDN0uqvOMwMz156dcVuiQkLTY+fiuaAUuoTt4d629nHxLBB7NjJDJqWaNxQ1Q/D8r6AT+GuyVvYB+3MbIbPk=

deploy:
  provider: releases
  api_key:
    secure: Cod8Afr5lS4R2LX5IB5KAckCxNyPWZL3fJb2qE62+Y4E41N9XK+0WETpvvCyg2hDFob60B+Zsk9lTTvnbtqnB72gZwleOe4gYg7ovRcrZL36iHR4XDE9MVAeZcBSKK1SwRIHwMWteQhNOEQw8OoHXzmzJnnitC9FsPdg8qiBk+M=
  file:
    - leanbean-api/pom.xml
    - leanbean-google/pom.xml
    - leanbean-mobile/context.xml
  skip_cleanup: true
  on:
    repo: wisobi/leanbean
