language: objective-c
xcode_project: leanbean-mobile/platforms/ios/LeanBean.xcodeproj
xcode_scheme: leanbean-mobile/platforms/ios/LeanBean
sudo: false

before_install:
  # Setup JVM and tools
  - export JAVA_HOME=$(/usr/libexec/java_home)
  - brew install ant
  - brew install maven
  # Install Android SDK
  - wget http://dl.google.com/android/android-sdk_r24.0.1-linux.tgz
  - tar xzf android-sdk_r24.0.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --all --filter build-tools-19.1.0,platform-tools,android-19,extra-android-support --no-ui --force
  # Install Cordova
  - npm install -g cordova
  # Install platforms and plugins for leanbean-mobile
  - cd leanbean-mobile
  - cordova platform add android
  - cordova platform add ios
  - cordova plugin add org.apache.cordova.device
  - cordova plugin add org.apache.cordova.statusbar
  - cordova plugin add https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin.git --variable URL_SCHEME=leanbean
  # Go back to root directory
  - cd ..

before_script:

script:
  # Build backend
  - pwd
  - cd leanbean-api
  - mvn install -DskipTests=true
  - mvn test
  - cd ..
  # Build Android and IOS
  - pwd
  - cd leanbean-mobile
  - cordova build android
  - cordova build ios